os: linux
dist: focal
language: generic
vm:
  use:
    name: 02_image
before_install:
  - sudo apt-get -y install libxml2-dev
addons:
  apt:
    update: true
script:
  - echo $TRAVIS_COMMIT_MESSAGE
  - sleep 2
  - echo "OK"
